#!/bin/bash
#SBATCH --nodes=NODES
#SBATCH --ntasks=NTASKS
#SBATCH --time=TIME     
#SBATCH --mail-type=MAIL-TYPE
#SBATCH --mail-user=MAIL-USER
#SBATCH --account=ACCOUNT
#SBATCH --job-name=JOB-NAME


module load CCEnv
module load StdEnv
module load nixpkgs/16.09
module load intel/2016.4
module load openmpi/2.1.1
module load quantumespresso/6.0 

srun EXECUTABLE < QE_INPUTFILE > QE_OUTPUTFILE

